# Generated by Django 5.0.6 on 2024-07-01 03:07
from django.db import migrations
from django.contrib.auth import get_user_model

User = get_user_model()


def create_data(apps, schema_editor):
    User.objects.create_superuser(
        username="coach1",
        email="coach1@example.com",
        password="coach1",
    )

    User.objects.create_superuser(
        username="coach2",
        email="coach2@example.com",
        password="coach2",
    )

    User.objects.create_superuser(
        username="student1",
        email="student1@example.com",
        password="student1",
    )

    User.objects.create_superuser(
        username="student2",
        email="student2@example.com",
        password="student2",
    )


class Migration(migrations.Migration):

    dependencies = [
        # specify the previous migration here
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]